
import { useState } from 'react';
import { Helmet } from 'react-helmet-async';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import ChatInterface from '@/components/ai/ChatInterface';
import InfoCards from '@/components/ai/InfoCards';
import { availableModels, ModelOption } from '@/services/aiAssistantService';

const AI = () => {
  // Get the first model as default
  const defaultModel = availableModels[0];
  const [selectedModel, setSelectedModel] = useState<string>(defaultModel.id);

  // Function to get current model details
  const getCurrentModel = (modelId: string): ModelOption => {
    return availableModels.find(model => model.id === modelId) || defaultModel;
  };

  return (
    <>
      <Helmet>
        <title>AI Assistant | JaguarForex</title>
        <meta name="description" content="Advanced AI assistant for forex trading insights" />
      </Helmet>
      
      <Navbar />
      
      <main className="min-h-screen bg-jaguarblue-950 pt-20 pb-16">
        <div className="container mx-auto px-4 max-w-6xl">
          {/* Header */}
          <div className="mb-8 text-center">
            <h1 className="text-3xl md:text-4xl font-bold mb-4">
              <span className="gradient-text">Advanced</span> AI Assistant
            </h1>
            <p className="text-gray-300 max-w-3xl mx-auto">
              Get personalized insights and analysis for your forex trading questions using state-of-the-art AI models.
            </p>
          </div>
          
          {/* Chat interface */}
          <ChatInterface 
            availableModels={availableModels}
            selectedModel={selectedModel}
            setSelectedModel={setSelectedModel}
          />
          
          {/* Info cards */}
          <InfoCards currentModel={getCurrentModel(selectedModel)} />
          
          {/* Disclaimer */}
          <div className="mt-6 text-center text-sm text-gray-500">
            <p>
              AI responses are generated by third-party models and should not be considered as financial advice.
              Always verify information and consult with professional financial advisors before making trading decisions.
            </p>
          </div>
        </div>
      </main>
      
      <Footer />
    </>
  );
};

export default AI;
